const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const out = path.resolve(__dirname,'..');
(async()=>{
  const targets=await (await fetch('http://127.0.0.1:9223/json')).json();
  const target=targets.find(t=>t.type==='page');assert.ok(target);
  const ws=new WebSocket(target.webSocketDebuggerUrl),pending=new Map(),errors=[];let next=0;
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  ws.onmessage=ev=>{const m=JSON.parse(ev.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++next;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const clickElement=async id=>{const p=await evaluate(`(()=>{const r=document.getElementById('${id}').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});};
  const shot=async name=>{const r=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,'docs','screenshots',name),Buffer.from(r.data,'base64'));};
  await send('Runtime.enable');await send('Page.enable');
  await send('Page.navigate',{url:'http://localhost:4173/?test'});await wait(600);
  assert.equal(await evaluate('typeof AshfallTest'),'object');
  await evaluate("document.getElementById('helpButton').click()");assert.equal(await evaluate('AshfallTest.state'),'help');
  await evaluate("document.getElementById('closeHelp').click()");await clickElement('startButton');await wait(50);
  assert.equal(await evaluate('AshfallTest.state'),'playing');
  assert.equal(await evaluate('AshfallTest.audioState'),'running');
  await send('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyD',key:'d'});await wait(400);
  await send('Input.dispatchKeyEvent',{type:'keyUp',code:'KeyD',key:'d'});
  assert.ok(await evaluate('AshfallTest.run.player.x>35'));
  await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:1100,y:450});
  await send('Input.dispatchMouseEvent',{type:'mousePressed',x:1100,y:450,button:'left',clickCount:1});await wait(500);
  await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:1100,y:450,button:'left',clickCount:1});
  assert.ok(await evaluate('AshfallTest.run.bullets.length>0'));
  await send('Input.dispatchKeyEvent',{type:'keyDown',code:'Space',key:' '});await wait(240);
  await send('Input.dispatchKeyEvent',{type:'keyUp',code:'Space',key:' '});assert.ok(await evaluate('AshfallTest.run.player.dashTimer>0'));
  await send('Input.dispatchKeyEvent',{type:'keyDown',code:'Escape',key:'Escape'});await send('Input.dispatchKeyEvent',{type:'keyUp',code:'Escape',key:'Escape'});
  assert.equal(await evaluate('AshfallTest.state'),'paused');
  await evaluate("document.getElementById('resumeButton').click();AshfallTest.addXp(20);AshfallTest.update(.01)");
  assert.equal(await evaluate('AshfallTest.state'),'upgrade');await shot('upgrades.png');
  await evaluate("document.querySelector('.upgrade-card').click()");assert.equal(await evaluate('AshfallTest.state'),'playing');
  await evaluate(`(()=>{const a=AshfallTest;a.start();a.seed(789);a.run.time=248;a.run.eliteWave=1;a.run.player.level=7;a.run.player.autoFire=true;a.mouse.active=true;a.mouse.x=1000;a.mouse.y=450;['scatter','pierce','orbit','orbit','width','echo'].forEach(id=>a.apply(id));a.run.player.invuln=100;for(let i=0;i<38;i++)a.spawnEnemy(['crawler','runner','brute','shooter','splitter'][i%5],Math.cos(i*2.4)*(180+i*6),Math.sin(i*2.4)*(180+i*6));for(let i=0;i<7;i++)a.run.ashes.push({x:-120+i*36,y:30,value:1,life:20,r:11,phase:i});a.startDash(1,0);a.step(.65);})()`);
  await wait(40);await shot('gameplay.png');
  await evaluate('AshfallTest.run.time=719.99;AshfallTest.update(.02)');await wait(60);await shot('boss.png');
  assert.equal(await evaluate('AshfallTest.run.boss.type'),'boss');
  await evaluate('AshfallTest.hurtEnemy(AshfallTest.run.boss,1e9)');assert.equal(await evaluate('AshfallTest.state'),'result');await shot('victory.png');
  await evaluate("document.getElementById('restartButton').click();AshfallTest.hurtPlayer(1e9)");assert.equal(await evaluate('AshfallTest.state'),'result');
  await evaluate("document.getElementById('titleButton').click()");assert.equal(await evaluate('AshfallTest.state'),'title');
  await send('Emulation.setDeviceMetricsOverride',{width:1024,height:640,deviceScaleFactor:1,mobile:false});await wait(120);await shot('compact-title.png');
  await evaluate("document.getElementById('startButton').click();AshfallTest.addXp(20);AshfallTest.update(.01)");await wait(100);await shot('compact-upgrades.png');
  const overflow=await evaluate("Array.from(document.querySelectorAll('.upgrade-card')).some(e=>e.getBoundingClientRect().bottom>innerHeight)");assert.equal(overflow,false);
  await send('Emulation.clearDeviceMetricsOverride');
  await send('Page.navigate',{url:'file:///'+out.replaceAll('\\','/')+'/index.html?test'});await wait(500);
  assert.equal(await evaluate('typeof AshfallTest'),'object');await clickElement('startButton');assert.equal(await evaluate('AshfallTest.state'),'playing');
  assert.equal(errors.length,0,JSON.stringify(errors));
  fs.writeFileSync(path.join(out,'browser-verification.json'),JSON.stringify({browser:'Chromium headless 1243',date:'2026-09-30',passed:['HTTP startup','title and help','audio activated by player click','real keyboard movement','mouse shooting','dash','pause and resume','upgrade UI click','combat rendering','final boss','victory','death','restart','title return','1024x640 layout','direct file startup'],runtimeErrors:errors.length},null,2));
  console.log('Browser verification: 16 checks passed, 0 runtime errors.');ws.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
